### ISSUE TITLE
File trên dropbox không tìm thấy

### ISSUE THREAD

**Issue by greeneley** [rain1024/playground#29]
Trong file classification.py. Có 1 đoạn code sh down default model về bằng link của dropbox. Nhưng link này bị hỏng. Có thể reup lại link được không ? 
```
#!/usr/bin/env bash

curl -L -o models/default_model.zip "https://www.dropbox.com/s/gztv0dpn3lzan51/models.zip?dl=0"

unzip models/default_model.zip -d models

rm -rf models/default_model.zip
```

**Comment by rain1024** [comment]
@greeneley 

Mình vừa cập nhật lại tutorial về huấn luyện hàm phân loại. Bạn xem ở đây nhé

https://github.com/undertheseanlp/playground/tree/master/plays/classification#training-a-vietnamese-text-classifier
